### ISSUE TITLE
pro commands

### ISSUE THREAD

**Issue by qyloxe** [cris691/environments#3]
documentation: 0
error checking in potentially disastrous server commands: 0

yep, definitely will be using this :-)

**Comment by cris691** [comment]
🤣 yeah you're right about docs. I guess it's small enough you could look and figure out, but I know there's not easy. Some people like it that way, figurer-outers, but I could document. Just lazy. Good point tho.

About the error checks could you provide some specific examples?

Sounds helpful. On both counts, please submit PRs! If you want :)

**Comment by qyloxe** [comment]
Hi,

Sure - just about every command is returning status code. If it failed for
some reason you shouldn't proceed with next commands. BUT it's just my
opinion, and in overall great job. I think in time it would be helpful to
others.
cheers!

**Comment by cris691** [comment]
Thank you
